spring:
  application:
    name: service-notification
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: Toosimple0531
server:
  port: 9002

