spring:
  cloud:
    gateway:
      routes:
        - id: service-driver
          uri: lb://service-driver
          predicates:
            - Path=/api/driver/**
        - id: service-matching
          uri: lb://service-matching
          predicates:
            - Path=/api/matching/**
        - id: service-notification
          uri: lb://service-notification
          predicates:
            - Path=/api/notification/**
        - id: service-payment
          uri: lb://service-payment
          predicates:
            - Path=/api/payment/**
        - id: service-ride
          uri: lb://service-ride
          predicates:
            - Path=/api/ride/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/user/**
      globalcors:         # 跨域CORS配置
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false  # 前后端域名不同必须 false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary