spring:
  application:
    name: service-user
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: 1779614188  # 建议使用环境变量或配置中心存储敏感信息
  datasource:
    url: jdbc:postgresql://ep-proud-credit-a1il33tr-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_nLg4bFAKVf2y
    driver-class-name: org.postgresql.Driver

server:
  port: 9005

jwt:
  secret: "6f9d8c7b-3a2e-4f1a-9b1e-23f9c4d8e7a6#@!XyZ"  # 替换为安全的密钥
  expire-minutes: 5

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 下划线自动转驼峰
  global-config:
    db-config:
      id-type: auto                     # 主键自增长