spring:
  application:
    name: service-matching
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: Cf1590753
  datasource:
    url: jdbc:postgresql://ep-proud-credit-a1il33tr-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_nLg4bFAKVf2y
    driver-class-name: org.postgresql.Driver
server:
  port: 9001
