spring:
  application:
    name: service-matching
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: Cf1590753
server:
  port: 9001

redis:
  host: localhost
  port: 6380
  password:
  timeout: 3000
  database: 1
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0