spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 3000
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  application:
    name: service-driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: Cf1590753
  datasource:
    url: jdbc:postgresql://ep-proud-credit-a1il33tr-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_nLg4bFAKVf2y
    driver-class-name: org.postgresql.Driver
  rabbitmq:

    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
server:
  port: 9000


jwt:
  secret: "6f9d8c7b-3a2e-4f1a-9b1e-23f9c4d8e7a6#@!XyZ"  # 替换为安全的密钥
  expire-minutes: 30


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 下划线自动转驼峰
  global-config:
    db-config:
      id-type: auto                     # 主键自增长

# 司机位置更新过滤配置
driver:
  location:
    filter:
      distance-threshold: 20    # 距离阈值（米）
      time-threshold: 10000     # 时间阈值（毫秒，10秒）