spring:
  application:
    name: service-ride
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: 1779614188


server:
  port: 9004

jwt:
  secret: "6f9d8c7b-3a2e-4f1a-9b1e-23f9c4d8e7a6#@!XyZ"  # 替换为安全的密钥
  expire-minutes: 5