spring:
  application:
    name: service-ride
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: 1779614188
#      config:
#        server-addr: 127.0.0.1:8848  # 配置中心地址
#        shared-configs: # 引入公共配置
#          - data-id: jwt-common.yml  # 公共JWT配置的data-id
#            group: DEFAULT_GROUP  # 对应Nacos中的配置分组
#            refresh: true  # 支持动态刷新（后续改密钥无需重启所有服务）

server:
  port: 9004

jwt:
  secret: "6f9d8c7b-3a2e-4f1a-9b1e-23f9c4d8e7a6#@!XyZ"  # 替换为安全的密钥
  expire-minutes: 5